# Generated by Django 3.1.4 on 2021-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=122)),
                ('reciver_name', models.CharField(max_length=122)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
