# Generated by Django 3.1.4 on 2021-07-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanksWorking', '0002_remove_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reciver_name',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='tdate',
        ),
    ]
